### PR TITLE
Add skin for Brazilian Air Force

### PR DESCRIPTION
**Pull request by thomaslfranca**
This adds a livery for the Brazilian Air Force
This is a screenshot of how it looks

image

### CODE REVIEW

**Comment by hoit626** [comment]
very good

**Comment by thomaslfranca** [comment]
Thank you

**Comment by thomaslfranca** [comment]
I think that opening a issue goes faster.

**Comment by thomaslfranca** [comment]
@kolos26 can you give some feedback about this PR?

**Comment by thomaslfranca** [comment]
Thank you

**Pull request closed without merging**
